name: 构建Thor镜像

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker login -u hejiale010426 -p ${{ secrets.DOCKER }} && docker build . --file src/Thor.Service/Dockerfile --tag hejiale010426/thor:latest && docker push hejiale010426/thor:latest
